### PR TITLE
chores: made changes in contributing.md

### PR DESCRIPTION
**Pull request by dibashthapa**
There are more changes to be made in `contributing.md` file. It's actually hard to configure `env` variables and this much information is not enough. 

Need to mention
1. `JWT_ALGO` ?? What are the allowed values ?
2. `JWT_EXPIRATION` , Are we allowed to use just seconds or strings , like `1s` , `2m` ?

### CODE REVIEW

**Comment by Neeraj319** [comment]
Thanks for the PR. I will make the changes that you've mentioned.

**Comment by Neeraj319** [comment]
done @dibashthapa.

**Comment by dibashthapa** [comment]
> done @dibashthapa.

Okay , can you also mention the route, where the params validation needs to be done ?

**Comment by Neeraj319** [comment]
Every route having some `id` as a parameter needs validation for now. You can visit the swagger docs and view them. Also, the default type for every id param is an integer.

**Comment by dibashthapa** [comment]
> Every route having some `id` as a parameter needs validation for now. You can visit the swagger docs and view them. Also, the default type for every id param is an integer.

Hmm okay , i will send PR for that, by tomorrow or Monday. Need to get my local machine setup done.

**Pull request merged**
